# -*- coding: utf-8 -*-
"""WageGapPerIndustry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nw_FuEm5TixbM436GJ-BJSY8ATB5jYVs

Import Necessary Files:
"""

import pandas as pd
import numpy as np
import seaborn as sns
import io

"""Get CVS files from local drive:"""

from google.colab import files
uploaded = files.upload()

"""Convert CVS into Python DataFrame:"""

DataSet = pd.read_csv(io.BytesIO(uploaded['inc_occ_gender.csv']))
DataSet = DataSet.drop(0)

DataSet

"""Replaces all 'Na' with zeroes (string)"""

for x in DataSet:
  for y in DataSet[x]:
    if y == 'Na':
      DataSet[x].replace({'Na': '0'}, inplace=True)

DataSet

"""Convert the String numbers in Integer numbers"""

for x in DataSet:
  if x == 'Occupation':
    continue
  else:
    DataSet[x] = pd.to_numeric(DataSet[x])

DataSet

"""Calculating Wage Gap:


"""

WageGap = 100*(DataSet['F_weekly']-DataSet['M_weekly'])/DataSet['All_weekly']
DataSet['WageGap'] = WageGap
DataSet = DataSet.round({'WageGap': 2})
DataSet

"""Largest Employer Data"""

DataSet.nlargest(1,['All_workers'])

"""Industry with the largest Wage Gap"""

DataSet.nsmallest(1,['WageGap'])

"""Clearly an issue with the Data that shows Female employees dont make anything on a weekly median bases. Have to remove zero values in (All_weekly, M_weekly, and F_weekly)"""

for x in DataSet:
  if x == 'Occupation':
    continue
  else:
    for y in DataSet[x]:
      if y == 0:
        indexNmbr = DataSet[DataSet[x] == 0].index
        DataSet.drop(indexNmbr, inplace=True)
DataSet

"""The industry with the highest wage gap:"""

DataSet.nsmallest(3,['WageGap'])

"""The industry with the lowest wage gap:"""

DataSet.nlargest(3,['WageGap'])

"""The industry with the most men vs women:"""

MenDataSet = DataSet.loc[DataSet['M_workers'] > DataSet['F_workers']]

MenDataSet.nlargest(3, ['M_workers'])

GenderDiff = MenDataSet['M_workers'] - MenDataSet['F_workers']
for x in GenderDiff.sort_values(ascending=False).index[:3]:
  print(MenDataSet.loc[x])

"""The industry with the most women vs men:"""

WomenDataSet = DataSet.loc[DataSet['F_workers'] > DataSet['M_workers']]

WomenDataSet.nlargest(3,['F_workers'])

GenderDiff = WomenDataSet['F_workers'] - WomenDataSet['M_workers']
for x in GenderDiff.sort_values(ascending=False).index[:3]:
  print(WomenDataSet.loc[x])

"""Top 3 highest paying roles and their wage difference to Men"""

DataSet.nlargest(3, ['F_weekly'])

"""Visualize the data:"""

sns.barplot(x = 'WageGap', y = 'Occupation', data = DataSet.sort_values(by = 'WageGap', ascending = False)[:15])